### ISSUE TITLE
Documenter l'affichage différent par partage / groupe

### ISSUE THREAD

**Issue by Guts** [isogeo/doc-portal-pixup-admin#1]

**Comment by leodarengosse** [comment]
Méthode pour deux partages (public, interne)

1. Créer le partage public vers le portail et lui partager le catalogue public  
2. Créer le partage interne vers le portail et lui partager le catalogue interne
3. Dans l'interface d'admin du portail, paramètres, affichage, pour chaque profil d'utilisateur : sélectionner le partage souhaité

Si une modification est faite dans APP (Exemple : une fiche est enlevée du catalogue public), il faut mettre à jour le cache des partages (Paramètres, Maintenance, Mettre à jour le cache des partages) pour que la fiche ne soit plus visible dans le portail pour le profil d'utilisateurs concerné.

Sinon, la modification sera effective au bout d'une heure (A vérifier)
